version: '3'
services:
  vsftpd:
    build: .
    container_name: vsftpd
    ports:
      - "20-21:20-21/tcp"
      - "21000-21010:21000-21010/tcp"
    volumes:
      - ./data:/home/vsftpd
      - ./certs:/etc/ssl/certs:ro
      - ./ssl_private:/etc/ssl/private:ro
    environment:
      - PASV_ADDRESS=192.168.1.165
      - PASV_MIN_PORT=21000
      - PASV_MAX_PORT=21010
    command: /bin/sh -c '/usr/sbin/run-vsftpd.sh & tail -f /dev/null'
