version: '3'
services:
  pureftpd:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      PUBLICHOST: "0.0.0.0"
      FTP_USER_NAME: "prueba"
      FTP_USER_PASS: "prueba"
      FTP_USER_HOME: "/home/ftpusers/ftpuser"
      MAXCLIENTS: "2"
      MAXCONNECTIONS: "2"
      TIMEOUT_IDLE: "3600"
      TLS: "1"
      ADDED_FLAGS: "--tls=2 --certfile=/etc/ssl/certs/pure-ftpd.pem --keyfile=/etc/ssl/private/pure-ftpd.key"
    volumes:
      - ./data:/home/ftpusers
      - ./certs:/etc/ssl/certs:ro
      - ./ssl_private:/etc/ssl/private:ro
